-- template_button 원본 시드 데이터 (온보딩 프리셋 61개)
-- 신규 DB 셋업 시 이 스크립트를 실행하면 됩니다.
-- preset_id는 auto_increment이므로 지정하지 않습니다 (아래 순서대로 1~61 자동 부여).

INSERT INTO template_button (button_name, category_name, created_at, deleted_at, display_order, icon_color, icon_name, template_id) VALUES
                                                                                                                                        ('침구류 세탁하기', '집', NOW(), NULL, 1, '#282471', 'clean', 1),
                                                                                                                                        ('잠옷 세탁하기', '집', NOW(), NULL, 2, '#536AFF', 'clothes', 1),
                                                                                                                                        ('냉장고 정리하기', '집', NOW(), NULL, 3, '#536AFF', 'clean', 1),
                                                                                                                                        ('쓰레기 버리기', '집', NOW(), NULL, 4, '#707070', 'clean', 1),
                                                                                                                                        ('설거지하기', '집', NOW(), NULL, 5, '#B7B7B7', 'clean', 1),
                                                                                                                                        ('집 청소하기', '집', NOW(), NULL, 6, '#000000', 'clean', 1),
                                                                                                                                        ('식물에 물 주기', '집', NOW(), NULL, 7, '#83FF65', 'plant', 1),
                                                                                                                                        ('반려동물 산책하기', '집', NOW(), NULL, 8, '#FFC760', 'dog', 1),
                                                                                                                                        ('카드값 납부', '생활', NOW(), NULL, 9, '#282471', 'pay', 1),
                                                                                                                                        ('보험료 납부', '생활', NOW(), NULL, 10, '#DE76FB', 'pay', 1),
                                                                                                                                        ('구독 프로그램 갱신', '생활', NOW(), NULL, 11, '#FF7171', 'pay', 1),
                                                                                                                                        ('적금 이체', '생활', NOW(), NULL, 12, '#536AFF', 'pay', 1),
                                                                                                                                        ('택배 반품', '생활', NOW(), NULL, 13, '#FFC760', 'shopping1', 1),
                                                                                                                                        ('일정 정리', '생활', NOW(), NULL, 14, '#FF7171', 'calendar', 1),
                                                                                                                                        ('정산 완료', '생활', NOW(), NULL, 15, '#83FF65', 'pay', 1),
                                                                                                                                        ('가스불 확인', '안전', NOW(), NULL, 16, '#FF7171', 'fire', 1),
                                                                                                                                        ('콘센트 확인', '안전', NOW(), NULL, 17, '#FCFF5E', 'lightning', 1),
                                                                                                                                        ('냉난방기 확인', '안전', NOW(), NULL, 18, '#63F2FF', 'lightning', 1),
                                                                                                                                        ('전등 확인', '안전', NOW(), NULL, 19, '#FFC760', 'lightning', 1),
                                                                                                                                        ('창문 확인', '안전', NOW(), NULL, 20, '#000000', 'lock', 1),
                                                                                                                                        ('문 잠금 확인', '안전', NOW(), NULL, 21, '#000000', 'door', 1),
                                                                                                                                        ('약 먹기', '건강', NOW(), NULL, 22, '#FF7171', 'medicine', 1),
                                                                                                                                        ('영양제 먹기', '건강', NOW(), NULL, 23, '#536AFF', 'medicine', 1),
                                                                                                                                        ('스트레칭 하기', '건강', NOW(), NULL, 24, '#63F2FF', 'gym', 1),
                                                                                                                                        ('운동하기', '건강', NOW(), NULL, 25, '#83FF65', 'gym', 1),
                                                                                                                                        ('혈당 체크', '건강', NOW(), NULL, 26, '#FF7171', 'medicine', 1),
                                                                                                                                        ('병원 방문', '건강', NOW(), NULL, 27, '#FF7171', 'health', 1),
                                                                                                                                        ('치과 방문', '건강', NOW(), NULL, 28, '#FF7171', 'health', 1),
                                                                                                                                        ('운동하기', '몸 관리', NOW(), NULL, 1, '#83FF65', 'gym', 2),
                                                                                                                                        ('스트레칭하기', '몸 관리', NOW(), NULL, 2, '#63F2FF', 'gym', 2),
                                                                                                                                        ('체중 체크', '몸 관리', NOW(), NULL, 3, '#B7B7B7', 'health', 2),
                                                                                                                                        ('혈당 체크', '몸 관리', NOW(), NULL, 4, '#FF7171', 'medicine', 2),
                                                                                                                                        ('피부 관리', '몸 관리', NOW(), NULL, 5, '#DE76FB', 'selfcare', 2),
                                                                                                                                        ('식단 관리', '몸 관리', NOW(), NULL, 6, '#FFC760', 'food', 2),
                                                                                                                                        ('명상', '마음 관리', NOW(), NULL, 7, '#83FF65', 'health', 2),
                                                                                                                                        ('일기 쓰기', '마음 관리', NOW(), NULL, 8, '#FCFF5E', 'pencil', 2),
                                                                                                                                        ('디지털 디톡스', '마음 관리', NOW(), NULL, 9, '#FCFF5E', 'health', 2),
                                                                                                                                        ('감정 기록하기', '마음 관리', NOW(), NULL, 10, '#FF8EEA', 'pencil', 2),
                                                                                                                                        ('취미 생활하기', '마음 관리', NOW(), NULL, 11, '#DE76FB', 'camera', 2),
                                                                                                                                        ('휴식', '마음 관리', NOW(), NULL, 12, '#536AFF', 'sleep', 2),
                                                                                                                                        ('일찍 자기', '생활 리듬', NOW(), NULL, 13, '#DE76FB', 'sleep', 2),
                                                                                                                                        ('영양제 먹기', '생활 리듬', NOW(), NULL, 14, '#536AFF', 'medicine', 2),
                                                                                                                                        ('카페인 줄이기', '생활 리듬', NOW(), NULL, 15, '#707070', 'health', 2),
                                                                                                                                        ('햇빛 보기', '생활 리듬', NOW(), NULL, 16, '#FCFF5E', 'sun', 2),
                                                                                                                                        ('물 마시기', '생활 리듬', NOW(), NULL, 17, '#63F2FF', 'liquid', 2),
                                                                                                                                        ('계획 세우기', '정돈', NOW(), NULL, 1, '#FFC760', 'calendar', 3),
                                                                                                                                        ('일정 정리', '정돈', NOW(), NULL, 2, '#FF7171', 'calendar', 3),
                                                                                                                                        ('메일 정리', '정돈', NOW(), NULL, 3, '#B7B7B7', 'chat', 3),
                                                                                                                                        ('연락 돌리기', '정돈', NOW(), NULL, 4, '#000000', 'call', 3),
                                                                                                                                        ('자료 정리', '정돈', NOW(), NULL, 5, '#83FF65', 'note', 3),
                                                                                                                                        ('언어 공부', '학습', NOW(), NULL, 6, '#FCFF5E', 'pencil', 3),
                                                                                                                                        ('코딩 공부', '학습', NOW(), NULL, 7, '#282471', 'pencil', 3),
                                                                                                                                        ('책 읽기', '학습', NOW(), NULL, 8, '#FCFF5E', 'book', 3),
                                                                                                                                        ('강의 듣기', '학습', NOW(), NULL, 9, '#FFC760', 'book', 3),
                                                                                                                                        ('자격증 공부', '학습', NOW(), NULL, 10, '#FF7171', 'pencil', 3),
                                                                                                                                        ('뉴스 읽기', '탐색', NOW(), NULL, 11, '#536AFF', 'book', 3),
                                                                                                                                        ('논문 읽기', '탐색', NOW(), NULL, 12, '#282471', 'book', 3),
                                                                                                                                        ('트렌드 서치', '탐색', NOW(), NULL, 13, '#FF8EEA', 'note', 3),
                                                                                                                                        ('일기 쓰기', '성장', NOW(), NULL, 14, '#FCFF5E', 'pencil', 3),
                                                                                                                                        ('아이디어 정리', '성장', NOW(), NULL, 15, '#FF8EEA', 'pencil', 3),
                                                                                                                                        ('포트폴리오 작업', '성장', NOW(), NULL, 16, '#DE76FB', 'pencil', 3);