-- template_button 원본 시드 데이터 (온보딩 프리셋 61개)
-- 신규 DB 셋업 시 01_insert_template_seed.sql 실행 후 이 스크립트를 실행하면 됩니다.
-- preset_id는 auto_increment이므로 지정하지 않습니다 (아래 순서대로 1~61 자동 부여).
--
-- icon_color는 HEX 코드가 아니라 색상 토큰 문자열입니다 (프론트에서 토큰별 실제 색상으로 매핑).
-- 사용 가능한 토큰: red, orange, yellow, green, cyan, blue, indigo, purple, pink, grey, darkgrey, black

INSERT INTO template_button (button_name, category_name, created_at, deleted_at, display_order, icon_color, icon_name, template_id) VALUES
('침구류 세탁하기', '집', NOW(), NULL, 1, 'indigo', 'clean', 1),
('잠옷 세탁하기', '집', NOW(), NULL, 2, 'blue', 'clothes', 1),
('냉장고 정리하기', '집', NOW(), NULL, 3, 'blue', 'clean', 1),
('쓰레기 버리기', '집', NOW(), NULL, 4, 'darkgrey', 'clean', 1),
('설거지하기', '집', NOW(), NULL, 5, 'grey', 'clean', 1),
('집 청소하기', '집', NOW(), NULL, 6, 'black', 'clean', 1),
('식물에 물 주기', '집', NOW(), NULL, 7, 'green', 'plant', 1),
('반려동물 산책하기', '집', NOW(), NULL, 8, 'orange', 'dog', 1),
('카드값 납부', '생활', NOW(), NULL, 9, 'indigo', 'pay', 1),
('보험료 납부', '생활', NOW(), NULL, 10, 'purple', 'pay', 1),
('구독 프로그램 갱신', '생활', NOW(), NULL, 11, 'red', 'pay', 1),
('적금 이체', '생활', NOW(), NULL, 12, 'blue', 'pay', 1),
('택배 반품', '생활', NOW(), NULL, 13, 'orange', 'shopping1', 1),
('일정 정리', '생활', NOW(), NULL, 14, 'red', 'calendar', 1),
('정산 완료', '생활', NOW(), NULL, 15, 'green', 'pay', 1),
('가스불 확인', '안전', NOW(), NULL, 16, 'red', 'fire', 1),
('콘센트 확인', '안전', NOW(), NULL, 17, 'yellow', 'lightning', 1),
('냉난방기 확인', '안전', NOW(), NULL, 18, 'cyan', 'lightning', 1),
('전등 확인', '안전', NOW(), NULL, 19, 'orange', 'lightning', 1),
('창문 확인', '안전', NOW(), NULL, 20, 'black', 'lock', 1),
('문 잠금 확인', '안전', NOW(), NULL, 21, 'black', 'door', 1),
('약 먹기', '건강', NOW(), NULL, 22, 'red', 'medicine', 1),
('영양제 먹기', '건강', NOW(), NULL, 23, 'blue', 'medicine', 1),
('스트레칭 하기', '건강', NOW(), NULL, 24, 'cyan', 'gym', 1),
('운동하기', '건강', NOW(), NULL, 25, 'green', 'gym', 1),
('혈당 체크', '건강', NOW(), NULL, 26, 'red', 'medicine', 1),
('병원 방문', '건강', NOW(), NULL, 27, 'red', 'health', 1),
('치과 방문', '건강', NOW(), NULL, 28, 'red', 'health', 1),
('운동하기', '몸 관리', NOW(), NULL, 1, 'green', 'gym', 2),
('스트레칭하기', '몸 관리', NOW(), NULL, 2, 'cyan', 'gym', 2),
('체중 체크', '몸 관리', NOW(), NULL, 3, 'grey', 'health', 2),
('혈당 체크', '몸 관리', NOW(), NULL, 4, 'red', 'medicine', 2),
('피부 관리', '몸 관리', NOW(), NULL, 5, 'purple', 'selfcare', 2),
('식단 관리', '몸 관리', NOW(), NULL, 6, 'orange', 'food', 2),
('명상', '마음 관리', NOW(), NULL, 7, 'green', 'health', 2),
('일기 쓰기', '마음 관리', NOW(), NULL, 8, 'yellow', 'pencil', 2),
('디지털 디톡스', '마음 관리', NOW(), NULL, 9, 'yellow', 'health', 2),
('감정 기록하기', '마음 관리', NOW(), NULL, 10, 'pink', 'pencil', 2),
('취미 생활하기', '마음 관리', NOW(), NULL, 11, 'purple', 'camera', 2),
('휴식', '마음 관리', NOW(), NULL, 12, 'blue', 'sleep', 2),
('일찍 자기', '생활 리듬', NOW(), NULL, 13, 'purple', 'sleep', 2),
('영양제 먹기', '생활 리듬', NOW(), NULL, 14, 'blue', 'medicine', 2),
('카페인 줄이기', '생활 리듬', NOW(), NULL, 15, 'darkgrey', 'health', 2),
('햇빛 보기', '생활 리듬', NOW(), NULL, 16, 'yellow', 'sun', 2),
('물 마시기', '생활 리듬', NOW(), NULL, 17, 'cyan', 'liquid', 2),
('계획 세우기', '정돈', NOW(), NULL, 1, 'orange', 'calendar', 3),
('일정 정리', '정돈', NOW(), NULL, 2, 'red', 'calendar', 3),
('메일 정리', '정돈', NOW(), NULL, 3, 'grey', 'chat', 3),
('연락 돌리기', '정돈', NOW(), NULL, 4, 'black', 'call', 3),
('자료 정리', '정돈', NOW(), NULL, 5, 'green', 'note', 3),
('언어 공부', '학습', NOW(), NULL, 6, 'yellow', 'pencil', 3),
('코딩 공부', '학습', NOW(), NULL, 7, 'indigo', 'pencil', 3),
('책 읽기', '학습', NOW(), NULL, 8, 'yellow', 'book', 3),
('강의 듣기', '학습', NOW(), NULL, 9, 'orange', 'book', 3),
('자격증 공부', '학습', NOW(), NULL, 10, 'red', 'pencil', 3),
('뉴스 읽기', '탐색', NOW(), NULL, 11, 'blue', 'book', 3),
('논문 읽기', '탐색', NOW(), NULL, 12, 'indigo', 'book', 3),
('트렌드 서치', '탐색', NOW(), NULL, 13, 'pink', 'note', 3),
('일기 쓰기', '성장', NOW(), NULL, 14, 'yellow', 'pencil', 3),
('아이디어 정리', '성장', NOW(), NULL, 15, 'pink', 'pencil', 3),
('포트폴리오 작업', '성장', NOW(), NULL, 16, 'purple', 'pencil', 3);
